### ISSUE TITLE
Unhandled Exception in Excalidraw Plugin for Goland

### ISSUE THREAD

**Issue by ykamran** [bric3/excalidraw-jetbrains-plugin#140] opened 2023-05-09 00:34 UTC
I encountered an unhandled exception while using the Excalidraw plugin in Goland. The exception details are as follows:

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@5e8e7c97, Dispatchers.Default]
java.lang.AssertionError: Not alive: Lifetime `Anonymous` [Terminating, executing=0, resources=4]
	at com.jetbrains.rd.util.lifetime.RLifetimeKt.assertAlive(RLifetime.kt:524)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.runJS(ExcalidrawWebViewController.kt:349)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.saveAsCoroutines(ExcalidrawWebViewController.kt:333)
	at com.github.bric3.excalidraw.editor.ExcalidrawEditor$saveCoroutines$1.invokeSuspend(ExcalidrawEditor.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@5e8e7c97, Dispatchers.Default]
```

I believe this issue is causing problems with the saving of Excalidraw diagrams. I would appreciate it if this issue could be investigated and resolved as soon as possible.

Thank you for your attention to this matter.

**Comment by bric3** [comment] 2023-05-09 09:31
Duplicate of 
* #20

THe new version is not published as there's some other problems that need some tackling, and I don't when I will have the time to fix those.

**Closed by bric3** 2023-05-09 09:31 UTC
