### ISSUE TITLE
java.lang.AssertionError: Not alive: Terminating

### ISSUE THREAD

**Issue by danielpacak** [bric3/excalidraw-jetbrains-plugin#20] opened 2021-09-29 13:16 UTC
Overall the plugin works great, but from time to time I'm receiving the following error.

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@77516895, Dispatchers.Default]

java.lang.AssertionError: Not alive: Terminating
	at com.jetbrains.rd.util.lifetime.RLifetimeKt.assertAlive(RLifetime.kt:347)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.runJS(ExcalidrawWebViewController.kt:349)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.saveAsCoroutines(ExcalidrawWebViewController.kt:333)
	at com.github.bric3.excalidraw.editor.ExcalidrawEditor$saveCoroutines$1.invokeSuspend(ExcalidrawEditor.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1262M
Cores: 16
Non-Bundled Plugins: com.github.bric3.excalidraw (0.3.2), org.openpolicyagent.opa-idea-plugin (0.6.0.0-211), org.jetbrains.plugins.go-template (212.4746.52), org.jetbrains.kotlin (212-1.5.31-release-546-IJ4638.7), com.intellij.kubernetes (212.5284.17), org.jetbrains.plugins.go (212.5284.31)
Kotlin: 212-1.5.31-release-546-IJ4638.7

**Comment by bric3** [comment] 2021-09-29 22:54
Yeah this assertion is there in the first place to understand messaging issues (between CEF and the JVM). From this stack trace I cannot identify the root cause, maybe it's related to closing / opening files, or switching editors.

Maybe I can make this error less of an issue.

**Comment by lestephane** [comment] 2022-04-25 07:27
What info would you like to receive? I just got the error, and still have the logs...

**Comment by bric3** [comment] 2022-04-25 08:38
@lestephane thanks
Yeah that could still be interesting. The nature of the exchange between the java handlers and JCef makes this exchange a bit unpractical around some edges, eg like closing an editor, etc.

**Closed** 2022-06-26 05:25 UTC
