### ISSUE TITLE
Crash and OOM after installing plugin and opening 2 drawings

### ISSUE THREAD

**Issue by ppar** [bric3/excalidraw-jetbrains-plugin#119] opened 2023-02-09 01:33 UTC
I know this is a really vague bug report, but here goes:

Today, after 
- installing the plugin, 
- opening 2 drawings (in 2 tabs inside the same "split"),
- switching the PyCharm window to full screen, and 
- switching from the 2nd tab to the first,

the following happened:
- PyCharm crashed
- Linux's OOM-killer went on its usual killing spree 
- The X server and entire KDE desktop crashed and/or were killed by OOM-killer.

I'm honestly not sure what the chain of events was -- system logs don't show the OOM-killer touching PyCharm, for example -- but switching to that 1st tab after fullscreening PyCharm seemed to be the trigger. 

So I'm suspecting either some memory leak in the plugin, or some bug related to the fullscreen mode / changed window dimensions that happened to crash PyCharm at the same time.

Environment:

Debian 11, KDE, 32 GB RAM

```
PyCharm 2021.3.2 (Community Edition)
Build #PC-213.6777.50, built on January 27, 2022
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

Error message (on next PyCharm startup)

```
Exception in plugin Excalidraw Integration (0.3.2)

Unhandled exception in [StandaloneCoroutine{Cancelling}@e86ee73, Dispatchers.Default]

java.lang.NullPointerException
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.runJS(ExcalidrawWebViewController.kt:352)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.saveAsCoroutines(ExcalidrawWebViewController.kt:333)
	at com.github.bric3.excalidraw.editor.ExcalidrawEditor$saveCoroutines$1.invokeSuspend(ExcalidrawEditor.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by bric3** [comment] 2023-02-09 13:16
Hi thanks for using the plugin and for taking time to write this report.

The NPE is unlikely to be the issue here, but I had definitely had some rough time with Chrome asynchronous handlers.
I don't know how this plugin could lead to the oomkiller taking actions. I would think it's unlikely caused by the plugin. But due to possible issues in the Jetbrains runtime, which includes JCef (the embedded Chrome).

I don't have a Linux desktop, so I cannot help much further on this.

2021.3.2 is kinda old, you may want to upgrade to a later version that possibly fixes this kind of bugs.

**Comment by bric3** [comment] 2024-01-09 00:12
Without reproducer I'm gonna close this one, feel free to re-open if you think this is wrongly closed.

**Closed by bric3** 2024-01-09 00:12 UTC
